# Agentic LLM Project Config
openai_api_key: "YOUR_OPENAI_API_KEY"
cohere_api_key: "YOUR_COHERE_API_KEY"
openrouter_api_key: "YOUR_OPENROUTER_API_KEY"
model_provider: "openai"  # or "openrouter"
model_name: "gpt-3.5-turbo"  # or başka bir model
embedding_model: "text-embedding-3-small"
data_dir: "./data/embeddings/"
rerank_with_cohere: true
